// A tool-managed block inside a notebook note's HTML content, regenerated
// from the link broker on every `link add`/`link rm`/`sync`. Owns exactly
// the span between its two sentinel paragraphs; never touches anything
// outside it.
//
// Marker choice: notebook's desktop editor (apps/desktop/src/components/
// NoteEditor.tsx) is TipTap/ProseMirror with a StarterKit-based schema and a
// fixed extension list (Underline, Link, Highlight, TaskList, Image, Table*,
// TextAlign, TextStyle, Color, FontFamily, FontSize, Superscript, Subscript,
// Callout, CodeCopyButton - see that file). Two marker shapes were
// considered and ruled out before landing on a literal text sentinel:
//
//   - An HTML comment (`<!-- ... -->`): ProseMirror's DOMParser (used by
//     `useEditor({ content })` and `editor.commands.setContent`) walks real
//     DOM nodes and only handles element (nodeType 1) and text (nodeType 3)
//     nodes - Comment nodes (nodeType 8) are unconditionally skipped by the
//     parser itself, before any schema/extension matching happens. Nothing
//     in the extension list above adds comment support. A comment marker
//     would therefore vanish the next time the note is opened and re-saved
//     in the desktop app, even though it survives untouched via direct
//     REST/SQLite writes (this tool's own transport).
//   - A wrapper element with a data attribute (e.g. `<div data-notebook-
//     links>`): none of the registered extensions defines a generic
//     passthrough node for arbitrary elements/attributes. ProseMirror's
//     default behavior for an element with no matching `parseDOM` rule is to
//     drop the element (and its attributes) but still parse its children in
//     place - so the *content* would survive an editor round-trip but the
//     attribute we'd need to relocate the block by would not, breaking
//     `findManagedBlock` on the next run after the note was opened in-app.
//
// A plain paragraph (`<p>`) is exactly what StarterKit's Paragraph node maps
// to, and text content inside it round-trips losslessly - it's the only
// shape of the three that is provably stable across an editor open/save.
// The regex below is deliberately tolerant of attributes ProseMirror might
// add to the `<p>` (e.g. a `style` from TextAlign) and of extra whitespace.

const BEGIN_LINE = "--- notebook-links:begin (do not edit below this line - regenerated by notebook-links) ---";
const END_LINE = "--- notebook-links:end ---";

const BLOCK_RE =
  /<p[^>]*>\s*-{2,}\s*notebook-links:begin\b[\s\S]*?<\/p>[\s\S]*?<p[^>]*>\s*-{2,}\s*notebook-links:end\b[\s\S]*?<\/p>/i;

/** Locates the managed block in `html`, or `null` if absent. */
export function findManagedBlock(html) {
  const match = BLOCK_RE.exec(html);
  if (!match) return null;
  return { start: match.index, end: match.index + match[0].length, text: match[0] };
}

function renderManagedBlock(innerHtml) {
  return `<p>${BEGIN_LINE}</p>${innerHtml}<p>${END_LINE}</p>`;
}

/**
 * Returns `html` with the managed block set to wrap `innerHtml` (inserted at
 * the end if absent), or removed entirely when `innerHtml` is falsy/empty.
 * Byte-identical in, byte-identical out when nothing actually changed -
 * callers should still compare old vs. new themselves before writing, since
 * this function has no way to skip the write itself.
 */
export function upsertManagedBlock(html, innerHtml) {
  const existing = findManagedBlock(html);
  if (!innerHtml) {
    if (!existing) return html;
    return html.slice(0, existing.start) + html.slice(existing.end);
  }
  const rendered = renderManagedBlock(innerHtml);
  if (existing) return html.slice(0, existing.start) + rendered + html.slice(existing.end);
  return html + rendered;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Renders one linked-entity paragraph for use as (part of) `innerHtml`. */
export function renderEntryParagraph(url, label) {
  return `<p><a href="${escapeHtml(url)}">${escapeHtml(label)}</a></p>`;
}
