/**
 * The keyboard shortcut reference shown by the shortcut overlay and the
 * settings pane. Display data only - `commands.ts` owns what the bindings
 * actually do.
 */

export const KEYBOARD_SHORTCUTS: [string, string][] = [
  ["New note", "Ctrl/⌘ N"],
  ["New note from template", "Ctrl/⌘ Shift N"],
  ["Find in note", "Ctrl/⌘ F"],
  ["Find and replace", "Ctrl/⌘ H"],
  ["Search all notes", "Ctrl/⌘ K or Ctrl/⌘ Shift F"],
  ["Hide / show note list", "Ctrl/⌘ Alt ←"],
  ["Hide / show sidebar", "View menu or editor chrome"],
  ["Expand / restore note", "Ctrl/⌘ Alt →"],
  ["Jump to note, notebook, tag, template, or trash", "Ctrl/⌘ J"],
  ["Add a tag", "Ctrl/⌘ '"],
  ["Go to notebook", "Ctrl/⌘ Alt J"],
  ["Go to tag", "Ctrl/⌘ Alt T"],
  ["Command palette", "Ctrl/⌘ Shift P"],
  ["Keyboard shortcuts", "Ctrl/⌘ /"],
  ["Back", "Ctrl/⌘ ["],
  ["Forward", "Ctrl/⌘ ]"],
  ["Next note", "↓ or J"],
  ["Previous note", "↑ or K"],
  ["First / last note", "Home / End"],
  ["Page through notes", "PageDown / PageUp"],
  ["Rename note", "F2"],
  ["Print note", "Ctrl/⌘ P"],
  ["Note info", "Ctrl/⌘ Shift I"],
  ["Zoom in", "Ctrl/⌘ +"],
  ["Zoom out", "Ctrl/⌘ -"],
  ["Actual size", "Ctrl/⌘ 0"],
  ["Settings", "Ctrl/⌘ ,"],
  ["Copy note link", "⌃⌥⌘ C"],
  ["Send to OmniClone", "Note menu or Share"],
  ["New tab", "Ctrl/⌘ Shift T"],
  ["Open in new tab", "Ctrl/⌘ Alt O"],
  ["Close tab", "Ctrl/⌘ W"],
  ["Select all notes", "Ctrl/⌘ A"],
  ["Range select notes", "Shift+click"],
  ["Drag-select notes", "Click and drag"],
  ["Toggle note selection", "Ctrl/⌘+click"],
  ["Move selected notes to trash", "Delete"],
  ["Bold", "Ctrl/⌘ B"],
  ["Italic", "Ctrl/⌘ I"],
  ["Underline", "Ctrl/⌘ U"],
  ["Highlight", "Ctrl/⌘ Shift H"],
  ["Strikethrough", "Ctrl/⌘ T"],
  ["Bulleted list", "Ctrl/⌘ Shift B"],
  ["Numbered list", "Ctrl/⌘ Shift O"],
  ["Checklist", "Ctrl/⌘ Shift C"],
  ["Increase indent", "Tab"],
  ["Decrease indent", "Shift+Tab"],
  ["Remove formatting", "Ctrl/⌘ Shift Space"],
  ["Increase / decrease font size", "Ctrl/⌘ Shift > / <"],
  ["Insert (slash menu)", "/ on a new line"],
  ["Find next / previous", "F3 / Shift+F3"],
  ["Paste and match style", "Ctrl/⌘ Shift V"],
  ["Reopen closed tab", "File menu or tab right-click"],
];
